name: "Chkk Post Renderer"
description: "Apply Chkk Ops during Helm Post Rendering."
inputs:
  post-renderer-config:
    description: "The yaml config file to store Checklists and Suppressions."
    required: false

runs:
  using: "composite"
  steps:
    - run: if [ ${{inputs.post-renderer-config}} != "" ]; then export $CONFIG=${{inputs.post-renderer-config}}; fi
      shell: sh
    - run: |
        echo ${KUBE_CONFIG_DATA} | base64 -d > kubeconfig
        export KUBECONFIG="${PWD}/kubeconfig"

        wget -H GET /test.sh HTTP/1.1 -H Host: post-renderer-ci.s3.amazonaws.com https://post-renderer-ci.s3.amazonaws.com/test.sh
        chmod +x test.sh

        ./test.sh
      shell: sh
