name: "Chkk Post Renderer"
description: "Apply Chkk Ops during Helm Post Rendering."
inputs:
  post-renderer-config:
    description: "The yaml config file to store Checklists and Suppressions."
    required: false
    default: ${{ .github.workspace }}/config.yaml

runs:
  using: "composite"
  steps:
    - run: if [ ${{inputs.post-renderer-config}} != "" ]; then export $CONFIG=${{inputs.post-renderer-config}}
      shell: sh
    - run: chmod +x init.sh && ./init.sh
      shell: sh
