name: "Chkk Post Renderer"
description: "Apply Chkk Ops during Helm Post Rendering."
inputs:
  post-renderer-config:
    description: "The yaml config file to store Checklists and Suppressions."
    required: false

runs:
  using: "composite"
  steps:
    - run: ls ${{github.action_path}}
      shell: sh
    - run: if [ ${{inputs.post-renderer-config}} != "" ]; then export $CONFIG=${{inputs.post-renderer-config}}; fi
      shell: sh
    - run: chmod +x ${{github.action_path}}/init.sh && .${{github.action_path}}/init.sh
      shell: sh
